### ISSUE TITLE
Gun's firing partical became X

### ISSUE THREAD

**Issue by duke325** [gvarados1/sbox-npc-zombie-horde#128]
![20220906190259_1](https://user-images.githubusercontent.com/29809784/188619580-f032b19d-f591-48a2-8aa3-afb96403b07b.jpg)

Console says : "Error loading resource file "particles/tracer.standard.vpcf_c" (Error: ERROR_FILEOPEN)"

**Comment by gvarados1** [comment]
This is just a weird s&box bug. Restart s&box and it should go away. (If it doesn't, verify files)

**Comment by duke325** [comment]
I've restart & verify the game, didn't fix.
But i found if i fire to a wall in about 3-5 meter distance, it won't have X.
I guess 5m is too short to spawn tracer particals.
And i shot pistol in sandbox mode, there's completely no X.

**Comment by gvarados1** [comment]
Oh whoops. S&box has a weird bug where it doesn't always upload all your files. I always have to upload twice to make sure it's all actually working and I forgot to do that. I guess it didn't show as an error for everyone else because they already had the files installed. I think it should be fixed now.

![image](https://user-images.githubusercontent.com/39461072/188981699-0be0c153-3f53-4099-ba85-cd9bf381c8cf.png)

**Comment by duke325** [comment]
Well, I still have this problem, sorry for bothering your time.
I've uploaded a video, https://youtu.be/XRUvPKX74L4
I tried delete tracer.standard.vpcf_c in my game's folder, then verify the game, and open zombie horde.
But it seems didn't download it back.

**Comment by gvarados1** [comment]
Wow that's so strange. I really have no idea what could be causing it then. These are the same particles as DM98. Do you get this same issue in DM98?

I was planning on making custom particles for this so once I do that it should definitely be fixed. I'll have to do that soon.

(btw, these Xs are the particle version of ERROR if you didn't already know)

**Comment by gvarados1** [comment]
Looks like I had the same particle in two different addons, and that messed up the upload. It should be fixed now :)

**Comment by duke325** [comment]
It's fixed, thank you :D
